name: Deploy Express App to Droplet

on:
  push:
    branches:
      - main  # or your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH keys
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DROPLET_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add SSH key passphrase
      run: |
        echo "$DROPLET_SSH_PASSPHRASE" | ssh-add ~/.ssh/id_rsa

    - name: Setup known_hosts
      run: |
        ssh-keyscan -H ${{ secrets.DROPLET_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to Droplet
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }} << 'EOF'
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # Load nvm

          cd ~/apps/arabic-juniors/backend-api
          git pull origin main

          pnpm install --frozen-lockfile  # Use pnpm instead of npm install
          pnpm build

          pm2 reload juniors-backend || pm2 start /dist/index.js --name juniors-backend
        EOF
